BASE_URL = "https://stellarburgers.nomoreparties.site"
USER_LOGIN = "/login"
USER_PROFILE = "/account/profile"
USER_REGISTER = "/register"
USER_FORGOT_PASSWORD = "/forgot-password"
USER_PASSWORD_RESET = "/reset-password"
ORDER_HISTORY = "/account/order-history"
FEED = "/feed"
